#!/bin/bash
### BEGIN INIT INFO
# Provides:          onetimed
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop one time download web server
### END INIT INFO

case "$1" in
  start)
    start-stop-daemon --start serve -c onetime -m -p /var/run/onetime.pid -a /opt/onetime/onetime &
  ;;
  stop)
    start-stop-daemon --stop -p /var/run/onetime.pid
  ;;
  *)
    echo "use: onetime start|stop"
  ;;
esac

